---
title: "Instant pot beef stew"
date: "2023-10-12"
categories: [soup, pressure]
---

This is pretty close to a one pot meal. Best served with a green salad or 
green vegetable with viniagrette and baguette.

_8 servings_

---

- 4 oz pork belly or thick sliced bacon, cut into lardons
- 2.5 pounds chuck roast, brisket, or other stew beef
- 6 oz crimini mushrooms
- 1 pkg pearl onions, 15-20
- 5 carrots
- 3 stalks celery
- 1 onion
- 3 cups chicken stock
- 3 packets gelatin
- 1 small can tomato paste
- 1 Tbsp soy sauce
- 2 tsp fish sauce or 5 anchovies
- 2 bay leaves
- 1 tsp dried thyme or 3 sprigs fresh
- 3 cloves of garlic, unpeeled
- 1/2 cup sherry, dry vermouth, brandy, or wine
- 4 T flour
- 1 pound potatoes, peeled
- 1.5 cups frozen peas

---

1. Set the pressure cooker to Saute (on low), and render the pork or bacon. You
may need to add a little water to help the rendering. Remove to a plate,
leaving 2 T or so of rendered fat.
1. Meanwhile, bring a pot of water to a boil. Add the pearl onions, and boil
about 30 seconds. This will make them easy to peel quickly. Remove, drain, and
let cool until you can peel them. You can trim the tops, but be careful with
the bottoms. Keeping the bottom will help them stay whole later.
1. Cut beef into 2-3 large "steaks". Season on both sides with salt and pepper.
Add to the pressure cooker, increase to medium, and sear on both sides. About
5-10 minutes per side. Remove to the same plate as the pork.
1. Add quartered mushrooms to the cooker until browned. Remove to a different
plate. Add the peeled pearl onions to the cooker until browned. Remove to the
same plate as the mushrooms.
1. Cut the onion in half from pole to pole, trim the root and peel. Cut 2
carrots in half long ways. Cut the celery and carrots into 3-4 inch pieces. Add
all of these and the garlic to the cooker and sear on 1-2 sides.
1. Combine the tomato paste, chicken stock, soy sauce, fish sauce, and gelatin
in a container and whisk to blend.
1. Cut the beef into chunks. Toss with the flour.
1. When the large vegetables are seared, add the liquor or wine and scrape to 
deglaze all the stuck bits. Allow to reduce by half (about 2-3 minutes).
1. Add the beef, pork, and the stock mix to the cooker. Add the bay leaves and
thyme. Seal the cooker and cook on high pressure for 30 minutes. Rapidly
release steam.
1. Meanwhile cut the remaining carrots and potatoes into chunks.
1. Open the cooker. Remove all the vegetables (which are now flavourless) and discard. Taste the liquid and adjust seasoning.
1. Add the potatoes, carrots, mushrooms and pearl onions. Seal the cooker and cook on high for 15 minutes. The rapidly release the steam.
1. Add the peas and stir. Taste again for seasoning. Serve immediately or
let cool and refrigerate for a day before serving.

::: aside

Adapted from: [Serious Eats](https://www.seriouseats.com/pressure-cooker-beef-stew-recipe) recipe by
J. Kenji López-Alt

:::

