---
title: "Asparagus chicken turmeric stir fry"
date: "2024-07-27"
categories: [asian, easy]
---

This is an easy, but flavourful stir fry that I make regularly. It only takes
about 20 minutes to make. I usually serve it with rice and sauteed greens 
(cooked with a 50/50 mixture of soy sauce and water).


---

- 1 lb asparagus
- 2 Tbsp flour or cornstarch
- 1 Tbsp ground turmeric
- salt to taste
- 1 Tbsp honey
- 1 Tbsp ground black pepper (or more)
- 1 lb boneless, skinless chicken thighs or breasts or turkey or tofu
- 3 Tbsp neutral oil

---

1. Trim bottoms of asparagus and cut into bitesize pieces.
1. Combine flour or cornstarch, turmeric, and a pinch of salt in a bowl large
enough to hold the chicken.
1. Combine honey, black pepper and 1/4 cup water in a small bowl.
1. Cut protein into bitesize pieces. Add to flour mixture and toss to coat.
1. Add oil to the pan and heat over medium. Once the oil shimmers, add chicken
and cook until browned all over, about 5 minutes, stirring to keep pieces
distinct. Add asparagus and cook for 2-3 minutes until brighter in colour, but
still crispy.
1. Add honey mixture to the pan, scraping up any stuck-on chicken bits. Add
additional water if needed. It should thicken into a sauce in about 2 minutes.
1. Serve with steamed white rice.