---
title: "Lentejas"
date: "2025-10-25"
categories: [soup]
---

This recipe came from José Andrés (Recipes for the People), but
the site seems to be taken down. There is a video on 
[YouTube](https://www.youtube.com/watch?v=LsomYk31oO8).

---

All quantities are approximately what I used the last time I
made this. Use whatever you like/have or leave it out.

- 1 lb dried brown or green lentils
- 3 onions
- 5 carrots (peeled)
- 1-2 tomatoes
- 1 leek
- 2 stalks celery
- 3 cloves garlic
- 1 bay leaf
- lots of ground paprika
- lots of cumin
- 3 medium boiling potatoes, peeled

---

1. Add the lentils, 1 onion, halved through the root, 1 carrot,
the tomatoes, the leek, the celery, the garlic, and the bay leaf 
to a large pot. Cover with 12 cups water and salt to taste. Bring 
to a boil then reduce to simmer for about 20 minutes, until the 
onion is soft.

2. Meanwhile, dice the remaining onions. Saute them in olive oil, 
letting them brown a bit. Then add the paprika (a lot, 
maybe 2-3 T). Saute for another minute until fragrant.

3. Remove the spent vegetables from the pot. Toss the bay leaf.
Add all vegetables to a blender with a bit of liquid from the
pot. Blend well, at high speed. 

4. Dump the blended vegetables back into the pot along with the
sauteed onion and the cumin.

5. Chop the remaining carrots into large chunks. Add to the pot.

6. With the heat off, "break" chunks off the potatoes. To do this,
use a small knife to cut part-way into the potato, then break off
the chunk. Keep doing this until you've finished the potato.

7. Cook until potatoes and carrots are soft.

Optionally, serve with a little red wine or sherry vinegar.
