---
title: "Faust's Pact"
date: "2023-10-23"
categories: [cocktail]
---

This was a favourite cocktail among my graduate school friends. We first
tried it at a now-closed bar called Embury near the Strip District in
Pittsburgh. The bartender moved to [Meat & Potatoes](https://meatandpotatoespgh.com), and we kept ordering it (off 
menu) on occasional trips downtown (conveniently located across from
Heinz Hall and the PSO). He eventually gave us the broad outlines of the
recipe. It's basically a Daiquiri made with Gin, but made extra spicy,
herbaceous, and delicious.

After reading through Dave Arnold's [Liquid Intelligence](https://www.powells.com/book/liquid-intelligence-the-art-science-of-the-perfect-cocktail-9780393089035), and with a big birthday 
approaching, I decided to try the "blender muddle", to see if it would
work as a batched cocktail to serve at a party (individual drinks would
be far too much time).

The blender muddle will only work if you make at least 2 (possibly 4) 
drinks at once. You need the blades of the blender completely submerged in
the alcohol to prevent the basil from turning brown.

_Recipe for 1 drink_

---

- 60 ml gin
- 30 ml lemon juice
- 20 ml 50/50 simple syrup
- 2-3 1/2 inch slices of jalapeño
- 1/2 inch knob of ginger, peeled
- 5 basil leaves
- Ground cayenne pepper

---

1. Combine gin, jalapeño, ginger, and basil in the bottom of a blender. 
Make sure the blades (and all the solids) are completely covered. If you
are planning to serve immediately, you can add the lemon juice. Blend for 
5-10 seconds until pureed.
1. Combine blender contents with simple syrup and lemon juice in a 
cocktail shaker. Add lots of ice and shake for 10-15 seconds.
1. Double strain into a chilled coupe glass and garnish with a bit of
cayenne pepper if desired.
ice


